### ISSUE TITLE
Identify conflict causing elements

### ISSUE THREAD

**Issue by lkoeln** [oodesign/duplicates-assistant#2]
I use the assistent and managed to reduce conflicts drastically. Unfortunately, I can't figure out which symbols exactly are causing the issue. When I right click on a rule, I only see the rules description but that doesn't help. I would like to see a list of the duplicated elements. 

![sketch-assistant](https://user-images.githubusercontent.com/11266750/98258362-147e5d00-1f81-11eb-819a-994fd31d422f.png)

**Comment by oodesign** [comment]
Hi @lkoeln ,

The Duplicates Assistant is designed to work side to side with the [Merge Duplicates](https://www.mergeduplicates.com) plugin, by flagging whether there are duplicate symbols or styles in your file.

Merge Duplicates is a non-free plugin, but if you'd like to give it a try, it does have a fully functional 7-day free trial that you may use to already get rid of some duplicates 😊.

By the way, we are fixing an issue that may cause the Duplicates Assistant to show more duplicates than it should. I'll make sure to let you know when we release a fix for it.

Thanks for reaching out!

**Comment by lkoeln** [comment]
Great, @oodesign ! Thanks for the quick response. I'll have a look at the plugin and wait for the fix.
