### ISSUE TITLE
Clicking warnings doesn't do anything

### ISSUE THREAD

**Issue by sylrs** [oodesign/duplicates-assistant#4]
When installing this assistant in Sketch 70.2 in my Library it shows some warnings, including duplicate symbols, duplicate layer styles, text styles. When I click these warnings they don't redirect me to any layer or artboard, nothing happens, making this assistant kind of useless for me, since I don't know where the duplicate items are. (Clicking the arrow doesn't do anything)

Also, the descriptions are cut off.
![image](https://user-images.githubusercontent.com/25570645/102505396-37bd2180-4082-11eb-8b70-b00777ed4d40.png)

**Comment by oodesign** [comment]
Hi @sylrs ,

The Duplicates Assistant is designed to work side to side with the [Merge Duplicates](https://www.mergeduplicates.com) plugin, by flagging whether there are duplicate symbols or styles in your file.

Merge Duplicates is a non-free plugin, but if you'd like to give it a try, it does have a fully functional 7-day free trial that you may use to already get rid of some duplicates 😊.

Thanks for reaching out!

**Comment by sylrs** [comment]
I wasn't aware of the plugin, thanks for the info.
